spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/sentryc_interview
    username: postgres
    password: 1234
    driver-class-name: org.postgresql.Driver

  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        '[format_sql]': true

  graphql:
    graphiql:
      enabled: true
